"""empty message

Revision ID: 2fa4047e8257
Revises: c1f5a7f3b9e1
Create Date: 2026-01-11 12:39:17.596046

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2fa4047e8257"
down_revision = "c1f5a7f3b9e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channels", sa.Column("account_name", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "account_name")
    # ### end Alembic commands ###
