"""empty message

Revision ID: aff34a6fd631
Revises: f9b6ffe18837
Create Date: 2026-01-11 13:20:48.684273

"""



# revision identifiers, used by Alembic.
revision = "aff34a6fd631"
down_revision = "f9b6ffe18837"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
