"""empty message

Revision ID: f9b6ffe18837
Revises: 2fa4047e8257
Create Date: 2026-01-11 13:10:50.071647

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f9b6ffe18837"
down_revision = "2fa4047e8257"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_index(op.f("ix_channels_channel_name"))
        batch_op.create_index(
            batch_op.f("ix_channels_channel_name"), ["channel_name"], unique=False
        )
        batch_op.create_unique_constraint(
            "_account_channel_uc", ["account_name", "channel_name"]
        )
        batch_op.create_index(
            batch_op.f("ix_channels_account_name"), ["account_name"], unique=False
        )
        batch_op.drop_column("cookies_path")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cookies_path", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.drop_index(batch_op.f("ix_channels_account_name"))
        batch_op.drop_constraint("_account_channel_uc", type_="unique")
        batch_op.drop_index(batch_op.f("ix_channels_channel_name"))
        batch_op.create_index(
            batch_op.f("ix_channels_channel_name"), ["channel_name"], unique=1
        )
    # ### end Alembic commands ###
